version: '3.8'

services:
  api:
    build:
      context: ./producer
    container_name: server
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_URL=jdbc:postgresql://postgres-database:5432/postgres
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_BOOTSTRAP_URL=kafka:9092
    depends_on:
      - postgres-database
      - kafka
    networks:
      - common-network

  postgres-database:
    image: postgres:12-alpine
    container_name: postgres-database
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'
    networks:
      - common-network

  email-notifications:
    build: .
    container_name: email-notification-service
    restart: on-failure
    environment:
      - MAIL_PORT=587
      - MAIL_LOGIN=e********
      - MAIL_PASSWORD=a*********
      - SPRING_PROFILES_ACTIVE=dev
      - ELASTICSEARCH_ADDRESS=http://elasticsearch:9200
      - SPRING_ELASTICSEARCH_URIS=elasticsearch:9200
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_BOOTSTRAP_URL=kafka:9092
    depends_on:
      - elasticsearch
      - kafka
    networks:
      - common-network

  elasticsearch:
    image: elasticsearch:8.6.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - common-network

  kibana:
    image: kibana:8.6.1
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - common-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - common-network

  kafka:
    hostname: kafka
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - common-network

networks:
  common-network:
    driver: bridge